# This is a "normal" job.
universe = vanilla

# Files to place stdout and stderr
output = process_$(Cluster)_$(Process).out
error = process_$(Cluster)_$(Process).err

# Job status log
log = process_$(Cluster)_$(Process).log

# Indicate this is a build job
+IsBuildJob = true
requirements = (Target.HasGluster == true) && (OpSysAndVer =?= "SL6") && (IsBuildSlot == true)

# Copy environment variables from the submit node
getenv = True
environment = "PATH=/bin:/usr/bin:/usr/local/bin LD_LIBRARY_PATH="

# Indicate if/when files should be transfered
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

# Indicate the executable to be run and any other input files needed
executable = build_pyne.bash
transfer_input_files = build_pyne.bash, common.bash, versions.bash

# Command line arguments for the executable
arguments = cubit mcnp5 mpi geant4 fluka

# Don't send emails
notification = never

# Request resources
request_cpus = 12
request_memory = 2GB
request_disk = 4GB

queue

