# This is a "normal" job.
universe = vanilla

# Files to place stdout and stderr
output = process_$(Cluster)_$(Process).out
error = process_$(Cluster)_$(Process).err

# Job status log
log = process_$(Cluster)_$(Process).log

# Indicate this is a build job
+IsBuildJob = true
requirements = (OpSysAndVer =?= "SL6") && ( IsBuildSlot == true )

# Copy environment variables from the submit node
getenv = True

# Indicate if/when files should be transfered
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

# Indicate the executable to be run and any other input files needed
executable = build_dagmc.bash
transfer_input_files = common.bash, build_dagmc.bash

# Command line arguments for the executable
arguments = my_username cubit mpi mcnp5

# Don't send emails
notification = never

# Request resources
request_cpus = 12
request_memory = 2GB
request_disk = 4GB

queue

