# This is a "normal" job.
universe = vanilla

# Files to place stdout and stderr
output = process_$(Cluster)_$(Process).out
error = process_$(Cluster)_$(Process).err

# Job status log
log = process_$(Cluster)_$(Process).log

# Indicate this is a build job
requirements = (Target.HasGluster == true) && (OpSysAndVer =?= "SL6")

# Copy environment variables from the submit node
getenv = True
environment = "PATH=/bin:/usr/bin:/usr/local/bin LD_LIBRARY_PATH= PYTHONPATH="

# Indicate if/when files should be transfered
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

# Indicate the executable to be run and any other input files needed
executable = cyclus_tests.bash
transfer_input_files = cyclus_tests.bash, build.bash, build_funcs.bash, common.bash

# Command line arguments for the executable
arguments =

# Don't send emails
notification = never

# Request resources
request_cpus = 1
request_memory = 4GB
request_disk = 32GB

queue
